### ISSUE TITLE
Building executables

### ISSUE THREAD

**Issue by vikramsandhu** [OxfordIonTrapGroup/mjolnir#2]
**NOTE:** Moving this topic to an issue, prior to submitting PR.

# Building executables

Building packaged executables is generally a pain in the neck - I wouldn't bother!

My own thoughts on this: conda itself is quite poor at keeping packages segregated when building executables with PyInstaller (I ended up resorting to virtualenv instead of conda). Python 3.6 and PyInstaller 3.4 seem to play nicely together. The built executable should be around 80MB.

[make_exe.txt](https://github.com/OxfordIonTrapGroup/mjolnir/files/5008250/make_exe.txt)

**Comment by dtcallcock** [comment]
From @ljstephenson  in #1 :

> Agree that binary packaging should be given up on - the primary reason for doing this was when artiq had a million dependencies it would crap out when installing on a lot of things, but moving to sipyco should make it pretty platform agnostic

Agreed.  Close this issue ?
